# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wNE9Gp5sfg_BFt_75xvpt-DsY4sRVkKG
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("Digital Campaign Performance Analytics")

# Load data
data = pd.read_csv('../data/campaign_data.csv')
data['CTR'] = data['Clicks'] / data['Impressions'] * 100
data['Conversion_Rate'] = data['Conversions'] / data['Clicks'] * 100

# Select platform
platform = st.selectbox("Select Platform", data['Platform'].unique())
filtered_data = data[data['Platform'] == platform]

# Display metrics
st.write("Campaign Metrics", filtered_data)

# Plot CTR
fig = px.bar(filtered_data, x='Campaign', y='CTR', title='CTR by Campaign')
st.plotly_chart(fig)

# Plot Conversion Rate
fig2 = px.bar(filtered_data, x='Campaign', y='Conversion_Rate', title='Conversion Rate by Campaign')
st.plotly_chart(fig2)