# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgNPDekyKGB9FSPmldAaQcEAYS43Neg5
"""

import pandas as pd

# Load data
data = pd.read_csv('../data/campaign_data.csv')

# Calculate metrics
data['CTR'] = data['Clicks'] / data['Impressions'] * 100
data['Conversion_Rate'] = data['Conversions'] / data['Clicks'] * 100
data['CPC'] = data['Spend'] / data['Clicks']

# Display summary
print(data.describe())

# Top campaigns by CTR
top_campaigns = data.sort_values(by='CTR', ascending=False)
print(top_campaigns)